### ISSUE TITLE
Can't define netflow version

### ISSUE THREAD

**Issue by b5y** [tehmaze/netflow#15]
I have nfcapd file with netflow v5 format and have tried to read it using netflow package. Unfortunately, it has not recognize it. Is it a bug or I miss something?

Here is my code:

```go
package main

import (
	"fmt"
	"time"
	"os"
	"log"
	"encoding/binary"
	"bytes"
	"io"
	"github.com/tehmaze/netflow/netflow1"
	"github.com/tehmaze/netflow/netflow5"
	"github.com/tehmaze/netflow/netflow6"
	"github.com/tehmaze/netflow/netflow7"
)

type Message interface {
}

func main() {
	startTime := time.Now()
	getFile := os.Args[1]
	fmt.Print("File name: ", getFile)
	fmt.Println()
	res, _ := fileReader(getFile)
	fmt.Println(res)
	endTime := time.Since(startTime)
	log.Printf("Program executes in %s", endTime)
}

func fileReader(fileName string) (Message, error) {
	file, err := os.Open(fileName)
	if err != nil {
		panic(err)
	}
	defer func() {
		if err := file.Close(); err != nil {
			panic(err)
		}
	}()

	data := [2]byte{}
	if _, err := file.Read(data[:]); err != nil {
		return nil, err
	}

	version := binary.BigEndian.Uint16(data[:])
	buffer := bytes.NewBuffer(data[:])
	mr := io.MultiReader(buffer, file)

	switch version {
	case netflow1.Version:
		return netflow1.Read(mr)

	case netflow5.Version:
		return netflow5.Read(mr)

	case netflow6.Version:
		return netflow6.Read(mr)

	case netflow7.Version:
		return netflow7.Read(mr)
	}
}
```

Here is a screenshot on ```switch version``` line:

![screen shot 2016-10-26 at 17 41 58](https://cloud.githubusercontent.com/assets/1110987/19731075/e1880072-9ba4-11e6-8b4e-feab3043240a.png)

File opens without any errors.

**Comment by adamlamar** [comment]
@b5y nfcapd writes an intermediate format to disk that is not standard netflow. Its meant to be read by the other nfdump tools. If you can get netflow in pcap form you should be able to read it with <a href="https://github.com/tehmaze/netflow/blob/master/cmd/nf-dump-pcap/main.go">nf-dump-pcap</a> or if you had raw netflow buffers then the program you wrote might work.

**Comment by b5y** [comment]
@adamlamar, Thank you for quick response!

Sadly, but there is [no](http://stackoverflow.com/questions/19480668/nfcapd-to-pcap-conversion) conversion tool from nfcapd to pcap. Back translation is possible.
