### ISSUE TITLE
No data in packets

### ISSUE THREAD

**Issue by kiranalii** [tehmaze/netflow#17]
Hi, 

I'm using netflow exporter for prometheus for reading netflow data, On the backend for translation of packets it is using these git repositories 

`	"github.com/tehmaze/netflow"
	"github.com/tehmaze/netflow/netflow5"
	"github.com/tehmaze/netflow/netflow9"
	"github.com/tehmaze/netflow/session"`

After receiving packets it reads the packet using Read function
`		m, err := d.Read(bytes.NewBuffer(buf[:chars]))
`

Earlier it was working fine but now when i try to read packet I can't see any data in DataFlowSets and TemplateSets fields and size of packets is greater than 40 to 1335.
`{{9 16 1203202659 1487056909 11865 6} [] [{{1 26}}] []}
`

I tried to debug but couldn't resolve the issue. Help would be appreciated. Thanks!

**Comment by tehmaze** [comment]
Could you provide us with example flows please?

**Comment by kiranalii** [comment]
I faced that issue for 2 days, but as soon as i changed port it started to work fine. It means there was something wrong with port. May be data gets corrupt.Thanks for help.
