### ISSUE TITLE
SysUptime incorrectly parsed as nanosecond

### ISSUE THREAD

**Issue by adamlamar** [tehmaze/netflow#5]
While parsing netflow v5, I noticed that the SysUptime field seems to be parsed incorrectly. <a href="http://www.cisco.com/c/en/us/td/docs/net_mgmt/netflow_collection_engine/3-6/user/guide/format.html">Various</a> <a href="http://www.cisco.com/en/US/technologies/tk648/tk362/technologies_white_paper09186a00800a3db9.html">documents</a/> describe SysUptime as the number of *milliseconds* since the device booted. In `netflow5/packet.go`, the code reads a 32-bit value and casts the value directly to a `time.Duration`, which leads them to be interpreted as *nanoseconds*:

```go
h.SysUptime = time.Duration(u)
```

In order to interpret `u` as a number of milliseconds, one could do this instead:

```go
h.SysUptime = time.Duration(u)*time.Millisecond
```

As an aside, the `First` and `Last` fields are based on `SysUptime`, but are `uint32` values in the struct. What do you think about changing these to `time.Duration` and parsing them as milliseconds as well?

**Comment by adamlamar** [comment]
Also, I'm happy to submit a PR for this issue if that would be useful.

**Comment by tehmaze** [comment]
Yes, please.

**Comment by adamlamar** [comment]
Very cool, thanks for doing this! I lost track of it.
