### ISSUE TITLE
Ipfix decode gives only one dataset per packet

### ISSUE THREAD

**Issue by mdsalman729** [tehmaze/netflow#9]
The ipfix message/packet contains 31 flows, but when I run the nf-dump file, I see it displaying only one flow per message/packet. Which means I am missing out on a number of flows. 

I verified it by dumping packets into a pcap file and running the nf-dump-pcap. The decoder seems to be picking up only one flow per packet.

**Comment by tehmaze** [comment]
Fixed in #11
